/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class euphony_lib_receiver_KissFFT */

#ifndef _Included_euphony_lib_receiver_KissFFT
#define _Included_euphony_lib_receiver_KissFFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     euphony_lib_receiver_KissFFT
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_euphony_lib_receiver_KissFFT_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     euphony_lib_receiver_KissFFT
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_euphony_lib_receiver_KissFFT_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     euphony_lib_receiver_KissFFT
 * Method:    spectrum
 * Signature: (JLjava/nio/ShortBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_euphony_lib_receiver_KissFFT_spectrum
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     euphony_lib_receiver_KissFFT
 * Method:    spectrum_for_phase
 * Signature: (JLjava/nio/ShortBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_euphony_lib_receiver_KissFFT_spectrum_1for_1phase
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     euphony_lib_receiver_KissFFT
 * Method:    getRealPart
 * Signature: (JLjava/nio/ShortBuffer;)V
 */
JNIEXPORT void JNICALL Java_euphony_lib_receiver_KissFFT_getRealPart
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     euphony_lib_receiver_KissFFT
 * Method:    getImagPart
 * Signature: (JLjava/nio/ShortBuffer;)V
 */
JNIEXPORT void JNICALL Java_euphony_lib_receiver_KissFFT_getImagPart
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
