execute_process(COMMAND ${ADB} -s ${SERIAL} shell LD_LIBRARY_PATH=${TARGET_TEST_LIB_DIR} ${TARGET_TEST_LIB_DIR}/testEuphony
                OUTPUT_VARIABLE GTEST_EUPHONY_OUTPUT
                RESULT_VARIABLE GTEST_RESULT
                ERROR_VARIABLE GTEST_ERROR_OUTPUT
                )

if( ${GTEST_RESULT} GREATER 0 )
    string(STRIP ${GTEST_EUPHONY_OUTPUT} GTEST_EUPHONY_OUTPUT)
    string(REPLACE "\n\n" "\r[NEXT]\r" GTEST_EUPHONY_OUTPUT ${GTEST_EUPHONY_OUTPUT})
    string(REPLACE "\n" "\r" GTEST_EUPHONY_OUTPUT ${GTEST_EUPHONY_OUTPUT})
    message(FATAL_ERROR "** Gtest Failure (${GTEST_RESULT}) **\r${GTEST_EUPHONY_OUTPUT}")
else()
    message("**** Gtest Success ****")
endif()