/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_euphony_fft_KissFFT */

#ifndef _Included_com_euphony_fft_KissFFT
#define _Included_com_euphony_fft_KissFFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_euphony_fft_KissFFT
 * Method:    create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_euphony_fft_KissFFT_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_euphony_fft_KissFFT
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_euphony_fft_KissFFT_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_euphony_fft_KissFFT
 * Method:    spectrum
 * Signature: (JLjava/nio/ShortBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_euphony_fft_KissFFT_spectrum
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_euphony_fft_KissFFT
 * Method:    getRealPart
 * Signature: (JLjava/nio/ShortBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_euphony_fft_KissFFT_getRealPart
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_euphony_fft_KissFFT
 * Method:    getImagPart
 * Signature: (JLjava/nio/ShortBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_euphony_fft_KissFFT_getImagPart
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
